language: ruby
sudo: false
rvm:
  - 2.3.0
services:
  - memcached
  - redis
env:
  - DB=postgresql
addons:
  postgresql: "9.4"
script:
  - RAILS_ENV=test bundle exec rails --trace db:test:prepare
before_script:
  - psql -c 'CREATE DATABASE zireael_test' -U postgres